### ISSUE TITLE
Nil pointer dereference in causal orderer

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#382]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xd6f06d]

goroutine 135 [running]:
github.com/iotaledger/hive.go/ds/shrinkingmap.(*ShrinkingMap[...]).Get(0x2b75de0?, {0x62, 0x60, 0x2e, 0x37, 0x9f, 0x19, 0x91, 0x4f, 0xc1, ...})
	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20230926122307-d671b36a4a65/shrinkingmap/shrinkingmap.go:92 +0x2d
github.com/iotaledger/hive.go/core/causalorder.(*CausalOrder[...]).decreaseUnorderedParentsCounter(0x2b75360, 0x31077236caecd7c2)
	/go/pkg/mod/github.com/iotaledger/hive.go/core@v1.0.0-rc.3.0.20230926122307-d671b36a4a65/causalorder/causalorder.go:187 +0x1b5
github.com/iotaledger/hive.go/core/causalorder.(*CausalOrder[...]).triggerChildIfReady(0x2b75360, 0x92a0f1)
	/go/pkg/mod/github.com/iotaledger/hive.go/core@v1.0.0-rc.3.0.20230926122307-d671b36a4a65/causalorder/causalorder.go:223 +0x1ca
github.com/iotaledger/hive.go/core/causalorder.(*CausalOrder[...]).propagateOrderToChildren.func1()
	/go/pkg/mod/github.com/iotaledger/hive.go/core@v1.0.0-rc.3.0.20230926122307-d671b36a4a65/causalorder/causalorder.go:250 +0x9e
github.com/iotaledger/hive.go/runtime/workerpool.(*Task).run(0xc065ec5890)
	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20230926122307-d671b36a4a65/workerpool/task.go:48 +0x72
github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).workerReadLoop(0xc000213c00)
	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20230926122307-d671b36a4a65/workerpool/workerpool.go:177 +0x25
github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).worker(0xc000213c00)
	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20230926122307-d671b36a4a65/workerpool/workerpool.go:159 +0x50
created by github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).startWorkers in goroutine 1
	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20230926122307-d671b36a4a65/workerpool/workerpool.go:151 +0x25
```

**Comment by alexsporn** [comment]
Can we close this if this is now unused with https://github.com/iotaledger/iota-core/pull/404 ?

**Comment by jonastheis** [comment]
+ delete the code in hive.go
