### ISSUE TITLE
Nil pointer in WarpSync

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#452]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc17dcc]

goroutine 1022729 [running]:
github.com/iotaledger/iota-core/pkg/protocol/chainmanager.(*Chain).LatestCommitment(0xc0000001f0?)
        /scratch/pkg/protocol/chainmanager/chain.go:54 +0x2c
github.com/iotaledger/iota-core/pkg/protocol.(*BlockDispatcher).warpSyncIfNecessary(0xc000646000, 0xc08eea6200, 0xd2066ec365257924?)
        /scratch/pkg/protocol/block_dispatcher.go:352 +0x8c
github.com/iotaledger/iota-core/pkg/protocol.(*BlockDispatcher).monitorLatestEngineCommitment.func1(0xc0ba02b9e0)
        /scratch/pkg/protocol/block_dispatcher.go:400 +0xfe
github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1(0xc07d0c1320?)
        /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231019175611-f85bce9102d1/event/events.go:88 +0x177
github.com/iotaledger/hive.go/ds/orderedmap.(*OrderedMap[...]).ForEach(0xd3baaf, 0xc001a376f8?)
        /go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231019175611-f85bce9102d1/orderedmap/orderedmap.go:130 +0xc4
github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger(0x0?, 0x0?)
        /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231019175611-f85bce9102d1/event/events.go:70 +0x71
github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1(0xc05391dbf0?)
        /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231019175611-f85bce9102d1/event/events.go:88 +0x177
github.com/iotaledger/hive.go/ds/orderedmap.(*OrderedMap[...]).ForEach(0xc0003f3a00, 0xc001a377f8?)
        /go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231019175611-f85bce9102d1/orderedmap/orderedmap.go:130 +0xc4
github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger(0xc0ba02b9e0?, 0xd2066ec365257924?)
        /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231019175611-f85bce9102d1/event/events.go:70 +0x71
github.com/iotaledger/iota-core/pkg/protocol/engine/notarization/slotnotarization.(*Manager).createCommitment(0xc000175d40, 0x1f0)
        /scratch/pkg/protocol/engine/notarization/slotnotarization/manager.go:266 +0xe6f
github.com/iotaledger/iota-core/pkg/protocol/engine/notarization/slotnotarization.(*Manager).tryCommitSlotUntil(0xc000175d40, 0x1fa)
        /scratch/pkg/protocol/engine/notarization/slotnotarization/manager.go:166 +0x92
github.com/iotaledger/iota-core/pkg/protocol/engine/notarization/slotnotarization.(*Manager).tryCommitUntil(0xc000175d40, 0x1fa)
        /scratch/pkg/protocol/engine/notarization/slotnotarization/manager.go:106 +0x45
github.com/iotaledger/iota-core/components/protocol.provide.func1.NewProvider.func15.1.1(0xc001a37ed8?)
        /scratch/pkg/protocol/engine/notarization/slotnotarization/manager.go:69 +0x131
github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1.1()
        /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231019175611-f85bce9102d1/event/events.go:86 +0x1f
github.com/iotaledger/hive.go/runtime/workerpool.(*Task).run(0xc08ffa24b0)
        /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231019175611-f85bce9102d1/workerpool/task.go:48 +0x72
github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).workerReadLoop(0xc06c0a6620)
        /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231019175611-f85bce9102d1/workerpool/workerpool.go:190 +0x25
github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).worker(0xc06c0a6620)
        /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231019175611-f85bce9102d1/workerpool/workerpool.go:170 +0x50
created by github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).startWorkers in goroutine 238
        /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231019175611-f85bce9102d1/workerpool/workerpool.go:162 +0x25
```

**Comment by piotrm50** [comment]
Hopefully will not be an issue in reactive chain manager.

**Comment by karimodm** [comment]
On hold because of #320

**Comment by jonastheis** [comment]
Since the code around warp sync changed drastically in #320 and #568 (ChainManager and block dispatcher do not exist anymore) this can be closed.
