### ISSUE TITLE
Failed to load root block in end-to-end test

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/iota-core#522]
```
]
2023-11-14T14:20:55.0368070Z node8 > [Candidate - ebfc0d52] Clock.AcceptedTimeUpdated: 2023-11-14 11:35:20.000000548 +0000 UTC [Slot 17]
2023-11-14T14:20:55.0370077Z node8 > [Candidate - ebfc0d52] Consensus.BlockGadget.BlockAccepted: BlockID(P1:17.3-node3:17) @ slot SlotIndex(17) committing to CommitmentID(0x42ecc25f165c3e02a654ff1f603b92b334c73da230d8d10f45e3c87286f16db10f000000:15)
2023-11-14T14:20:55.0370790Z node8 > [Candidate - ebfc0d52] Scheduler.BlockEnqueued: BlockID(P1:17.3-node3:17)
2023-11-14T14:20:55.0372332Z node6 > Network.WarpSyncResponseReceived: from 12D3KooWBV9oCyHd87AFRFe6jy8eT9ygzZSyUR5kQnZA45NYGfxH CommitmentID(0xd2d91ab9b0ce0bbc2b22b7c049bb8891156076cbfd1c2862962a4d42c4ac5cc212000000:18)
2023-11-14T14:20:55.0373794Z node6 > Network.WarpSyncResponseReceived: from 12D3KooWGthTUjyvpqM1tj1kYXLvPAuhQhXUCSpDy1rTULP9jdKi CommitmentID(0xd2d91ab9b0ce0bbc2b22b7c049bb8891156076cbfd1c2862962a4d42c4ac5cc212000000:18)
2023-11-14T14:20:55.0375356Z node6 > Network.WarpSyncResponseReceived: from 12D3KooWFays8AtZRkVNuXaXrioiSDHNVBXKqauQWg4yYpfqHpBp CommitmentID(0xd2d91ab9b0ce0bbc2b22b7c049bb8891156076cbfd1c2862962a4d42c4ac5cc212000000:18)
2023-11-14T14:20:55.0375975Z node6 > [Candidate - ebfbb687] Scheduler.BlockScheduled: BlockID(P1:17.3-node4:17)
2023-11-14T14:20:55.0377577Z node6 > Network.WarpSyncResponseReceived: from 12D3KooWHygHc9B3xK4cXNHFYJdPX9vsk5cZUWcMHjZRtpUL5msK CommitmentID(0xd2d91ab9b0ce0bbc2b22b7c049bb8891156076cbfd1c2862962a4d42c4ac5cc212000000:18)
2023-11-14T14:20:55.0378138Z node8 > [Candidate - ebfc0d52] Booker.BlockBooked: BlockID(P1:17.3-node3:17)
2023-11-14T14:20:55.0378865Z node8 > [Candidate - ebfc0d52] Scheduler.BlockEnqueued: BlockID(P1:17.2-node0:17)
2023-11-14T14:20:55.0379500Z node8 > [Candidate - ebfc0d52] Booker.BlockBooked: BlockID(P1:17.2-node0:17)
2023-11-14T14:20:55.0380091Z node8 > [Candidate - ebfc0d52] Scheduler.BlockEnqueued: BlockID(P1:17.1-node3:17)
2023-11-14T14:20:55.0380734Z node8 > [Candidate - ebfc0d52] Booker.BlockBooked: BlockID(P1:17.1-node3:17)
2023-11-14T14:20:55.0381470Z node8 > [Candidate - ebfc0d52] Scheduler.BlockEnqueued: BlockID(P1:17.0-node0:17)
2023-11-14T14:20:55.0382113Z node6 > [Candidate - ebfbb687] Scheduler.BlockScheduled: BlockID(P1:17.3-node2:17)
2023-11-14T14:20:55.0382794Z node6 > [Candidate - ebfbb687] Scheduler.BlockScheduled: BlockID(P1:17.1-node1:17)
2023-11-14T14:20:55.0383393Z node6 > [Candidate - ebfbb687] Booker.BlockBooked: BlockID(P1:17.0-node0:17)
2023-11-14T14:20:55.0384148Z node6 > [Candidate - ebfbb687] SybilProtection.BlockProcessed: BlockID(P1:17.0-node0:17)
2023-11-14T14:20:55.0384824Z node6 > [Candidate - ebfbb687] CommitmentFilter.BlockAllowed: BlockID(P1:17.0-node0:17)
2023-11-14T14:20:55.0385487Z node6 > [Candidate - ebfbb687] Scheduler.BlockScheduled: BlockID(P1:17.2-node0:17)
2023-11-14T14:20:55.0386113Z node6 > [Candidate - ebfbb687] BlockDAG.BlockSolid: BlockID(P1:17.0-node0:17)
2023-11-14T14:20:55.0386704Z node7 > [Candidate - ebfc9961] Scheduler.BlockScheduled: BlockID(P1:17.2-node3:17)
2023-11-14T14:20:55.0387499Z node7 > [Candidate - ebfc9961] Scheduler.BlockScheduled: BlockID(P1:17.3-node4:17)
2023-11-14T14:20:55.0388098Z node7 > [Candidate - ebfc9961] Scheduler.BlockScheduled: BlockID(P1:17.0-node0:17)
2023-11-14T14:20:55.0389083Z node7 > [Candidate - ebfc9961] Scheduler.BlockScheduled: BlockID(P1:17.3-node1:17)
2023-11-14T14:20:55.0392035Z node8 > [Candidate - ebfc0d52] Consensus.BlockGadget.BlockPreConfirmed: BlockID(P1:17.0-node0:17) CommitmentID(0xa5f13d767c191723d9f91dfccc4fdaf44c426a3fe1cb0f864f5994d5dc1645c80e000000:14)
2023-11-14T14:20:55.0395028Z node8 > [Candidate - ebfc0d52] Consensus.BlockGadget.BlockPreConfirmed: BlockID(P1:17.0-node1:17) CommitmentID(0xa5f13d767c191723d9f91dfccc4fdaf44c426a3fe1cb0f864f5994d5dc1645c80e000000:14)
2023-11-14T14:20:55.0397557Z node8 > [Candidate - ebfc0d52] Consensus.BlockGadget.BlockPreConfirmed: BlockID(P1:17.0-node4:17) CommitmentID(0xa5f13d767c191723d9f91dfccc4fdaf44c426a3fe1cb0f864f5994d5dc1645c80e000000:14)
2023-11-14T14:20:55.0400184Z node8 > [Candidate - ebfc0d52] Consensus.BlockGadget.BlockPreConfirmed: BlockID(P1:17.0-node2:17) CommitmentID(0xa5f13d767c191723d9f91dfccc4fdaf44c426a3fe1cb0f864f5994d5dc1645c80e000000:14)
2023-11-14T14:20:55.0403242Z panic: trying to access closed kvstore: failed to retrieve from KV store: failed to get value for key BlockID(P1:17.3-node1:17): failed to load root block BlockID(P1:17.3-node1:17)
2023-11-14T14:20:55.0403287Z 
2023-11-14T14:20:55.0403651Z goroutine 289170 [running]:
2023-11-14T14:20:55.0406307Z github.com/iotaledger/iota-core/pkg/protocol/engine/eviction.(*State).RootBlockCommitmentID(0xc018617630, {0x5a, 0xe, 0x3a, 0xf1, 0xe5, 0x27, 0x94, 0xf2, 0x1e, ...})
2023-11-14T14:20:55.0408420Z 	/actions-runner/_work/iota-core/iota-core/pkg/protocol/engine/eviction/state.go:167 +0x31a
2023-11-14T14:20:55.0410785Z github.com/iotaledger/iota-core/pkg/protocol/engine/blocks.(*Blocks).Block(0xc01b8716c0, {0x5a, 0xe, 0x3a, 0xf1, 0xe5, 0x27, 0x94, 0xf2, 0x1e, ...})
2023-11-14T14:20:55.0412229Z 	/actions-runner/_work/iota-core/iota-core/pkg/protocol/engine/blocks/blocks.go:42 +0xd8
2023-11-14T14:20:55.0414835Z github.com/iotaledger/iota-core/pkg/protocol/engine/congestioncontrol/scheduler/drr.(*Scheduler).updateChildrenWithoutLocking(0xc0043d9140, 0x865bca?)
2023-11-14T14:20:55.0416839Z 	/actions-runner/_work/iota-core/iota-core/pkg/protocol/engine/congestioncontrol/scheduler/drr/scheduler.go:722 +0xb3
2023-11-14T14:20:55.0441759Z github.com/iotaledger/iota-core/pkg/protocol/engine/congestioncontrol/scheduler/drr.(*Scheduler).updateChildrenWithLocking(0xc0043d9140, 0xc00f1c5ef8?)
2023-11-14T14:20:55.0443973Z 	/actions-runner/_work/iota-core/iota-core/pkg/protocol/engine/congestioncontrol/scheduler/drr/scheduler.go:715 +0x75
2023-11-14T14:20:55.0447187Z github.com/iotaledger/iota-core/pkg/protocol/engine/congestioncontrol/scheduler/drr.(*Scheduler).scheduleValidationBlock(0xc0043d9140, 0x4024000000000000?, 0xc00ee02e00)
2023-11-14T14:20:55.0449331Z 	/actions-runner/_work/iota-core/iota-core/pkg/protocol/engine/congestioncontrol/scheduler/drr/scheduler.go:405 +0x54
2023-11-14T14:20:55.0451657Z github.com/iotaledger/iota-core/pkg/protocol/engine/congestioncontrol/scheduler/drr.(*Scheduler).validatorLoop(0xc0043d9140, 0xc00ee02e00)
2023-11-14T14:20:55.0453723Z 	/actions-runner/_work/iota-core/iota-core/pkg/protocol/engine/congestioncontrol/scheduler/drr/scheduler.go:381 +0x9f
2023-11-14T14:20:55.0456337Z created by github.com/iotaledger/iota-core/pkg/protocol/engine/congestioncontrol/scheduler/drr.(*Scheduler).addValidator in goroutine 280213
2023-11-14T14:20:55.0458404Z 	/actions-runner/_work/iota-core/iota-core/pkg/protocol/engine/congestioncontrol/scheduler/drr/scheduler.go:748 +0xf9
2023-11-14T14:20:55.0459203Z FAIL	github.com/iotaledger/iota-core/pkg/tests	155.183s
2023-11-14T14:20:55.0459428Z FAIL
2023-11-14T14:20:55.0486942Z ##[error]Process completed with exit code 1.
2023-11-14T14:20:55.0688292Z Post job cleanup.
```

**Comment by karimodm** [comment]
Should be addressed by https://github.com/iotaledger/iota-core/pull/441/files#diff-7275a33b517fe648226f838379bf48e4e58010ed10b7c8448f5bc679d221d5c4
