### ISSUE TITLE
UpgradeSignalling test fails randomly

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/iota-core#523]
Happened randomly a few times in the CI

```
2023-11-14T14:25:27.9053305Z nodeB > [Main - 4c69a680] Consensus.BlockGadget.BlockPreAccepted: BlockID(63.3-nodeA:63) CommitmentID(0x9540150b8413d30b1df49be5b328060987ddad8beffe3c6d81e58886e9398d3a3d000000:61)
2023-11-14T14:25:27.9053824Z nodeB > [Main - 4c69a680] BlockDAG.BlockAttached: BlockID(64.1-nodeB:64)
2023-11-14T14:25:27.9055275Z nodeB > [Main - 4c69a680] Consensus.BlockGadget.BlockPreAccepted: BlockID(63.3-nodeD:63) CommitmentID(0x9540150b8413d30b1df49be5b328060987ddad8beffe3c6d81e58886e9398d3a3d000000:61)
2023-11-14T14:25:27.9056752Z nodeB > [Main - 4c69a680] Consensus.BlockGadget.BlockPreConfirmed: BlockID(63.3-nodeA:63) CommitmentID(0x9540150b8413d30b1df49be5b328060987ddad8beffe3c6d81e58886e9398d3a3d000000:61)
2023-11-14T14:25:27.9058081Z nodeB > [Main - 4c69a680] Consensus.BlockGadget.BlockPreConfirmed: BlockID(63.3-nodeD:63) CommitmentID(0x9540150b8413d30b1df49be5b328060987ddad8beffe3c6d81e58886e9398d3a3d000000:61)
2023-11-14T14:25:27.9058556Z nodeB > [Main - 4c69a680] Scheduler.BlockEnqueued: BlockID(64.1-nodeB:64)
2023-11-14T14:25:27.9058992Z nodeB > [Main - 4c69a680] Booker.BlockBooked: BlockID(64.1-nodeB:64)
2023-11-14T14:25:27.9059572Z nodeB > [Main - 4c69a680] SybilProtection.BlockProcessed: BlockID(64.1-nodeB:64)
2023-11-14T14:25:27.9060135Z nodeB > [Main - 4c69a680] CommitmentFilter.BlockAllowed: BlockID(64.1-nodeB:64)
2023-11-14T14:25:27.9060644Z nodeB > [Main - 4c69a680] BlockDAG.BlockSolid: BlockID(64.1-nodeB:64)
2023-11-14T14:25:27.9061123Z nodeB > [Main - 4c69a680] Scheduler.BlockScheduled: BlockID(64.1-nodeB:64)
2023-11-14T14:25:27.9062585Z nodeD > Network.Error: from 12D3KooWRERs2Wco4VpNqQEZmUCFpDefT9aqaWvQBUEntEHTERRB protocol parameters for version 5 are not set: failed to retrieve API for version 5: failed to deserialize block
2023-11-14T14:25:27.9063852Z nodeF > Network.Error: from 12D3KooWRERs2Wco4VpNqQEZmUCFpDefT9aqaWvQBUEntEHTERRB protocol parameters for version 5 are not set: failed to retrieve API for version 5: failed to deserialize block
2023-11-14T14:25:27.9065106Z nodeG > Network.Error: from 12D3KooWRERs2Wco4VpNqQEZmUCFpDefT9aqaWvQBUEntEHTERRB protocol parameters for version 5 are not set: failed to retrieve API for version 5: failed to deserialize block
2023-11-14T14:25:27.9066473Z nodeA > Network.Error: from 12D3KooWRERs2Wco4VpNqQEZmUCFpDefT9aqaWvQBUEntEHTERRB protocol parameters for version 5 are not set: failed to retrieve API for version 5: failed to deserialize block
2023-11-14T14:25:27.9067386Z nodeC > Network.BlockReceived: from 12D3KooWRERs2Wco4VpNqQEZmUCFpDefT9aqaWvQBUEntEHTERRB BlockID(64.1-nodeB:64) - 64
2023-11-14T14:25:27.9067868Z nodeC > [Main - 4cb478e0] Filter.BlockPreAllowed: BlockID(64.1-nodeB:64)
2023-11-14T14:25:27.9068340Z nodeC > [Main - 4cb478e0] Engine.BlockProcessed: BlockID(64.1-nodeB:64)
2023-11-14T14:25:27.9068781Z nodeC > [Main - 4cb478e0] BlockRequester.Tick: BlockID(64.0-nodeB:64)
2023-11-14T14:25:27.9069246Z nodeC > [Main - 4cb478e0] BlockDAG.BlockMissing: BlockID(64.0-nodeB:64)
2023-11-14T14:25:27.9069714Z nodeC > [Main - 4cb478e0] BlockDAG.BlockAttached: BlockID(64.1-nodeB:64)
2023-11-14T14:25:27.9070633Z nodeD > Network.BlockRequestReceived: from 12D3KooWApCSEARnh4DK5DUqKoMHiZ3Pn1Atggtes9wZUMbojyfi BlockID(64.0-nodeB:64)
2023-11-14T14:25:27.9071171Z nodeC > [Main - 4cb478e0] BlockDAG.MissingBlockAttached: BlockID(64.0-nodeB:64)
2023-11-14T14:25:27.9071467Z panic: protocol parameters for version 5 are not set
2023-11-14T14:25:27.9071490Z 
2023-11-14T14:25:27.9071667Z goroutine 337270 [running]:
2023-11-14T14:25:27.9072057Z github.com/iotaledger/hive.go/lo.PanicOnErr[...](...)
2023-11-14T14:25:27.9073449Z 	/home/runner/go/pkg/mod/github.com/iotaledger/hive.go/lo@v0.0.0-20231110191152-7135670285dc/lo.go:206
2023-11-14T14:25:27.9074046Z github.com/iotaledger/iota.go/v4/api.(*EpochBasedProvider).APIForSlot(0xc01b188200, 0x40)
2023-11-14T14:25:27.9075146Z 	/home/runner/go/pkg/mod/github.com/iotaledger/iota.go/v4@v4.0.0-20231110131407-263d0662856b/api/epoch_based_provider.go:142 +0x105
2023-11-14T14:25:27.9076149Z github.com/iotaledger/iota-core/pkg/storage/prunable.(*Prunable).getKVStoreFromSlot(0xc010a567e0, 0x40, {0xc0087add3f, 0x1, 0x1})
2023-11-14T14:25:27.9076828Z 	/actions-runner/_work/iota-core/iota-core/pkg/storage/prunable/prunable_slot.go:28 +0x43
2023-11-14T14:25:27.9077512Z github.com/iotaledger/iota-core/pkg/storage/prunable.(*Prunable).Blocks(0xc010a567e0, 0x40)
2023-11-14T14:25:27.9078191Z 	/actions-runner/_work/iota-core/iota-core/pkg/storage/prunable/prunable_slot.go:34 +0x3d
2023-11-14T14:25:27.9078851Z github.com/iotaledger/iota-core/pkg/storage.(*Storage).Blocks(0xc00a3f6240, 0x40)
2023-11-14T14:25:27.9079494Z 	/actions-runner/_work/iota-core/iota-core/pkg/storage/storage_prunable.go:42 +0x6e
2023-11-14T14:25:27.9080562Z github.com/iotaledger/iota-core/pkg/protocol/engine.(*Engine).Block(0xc01e7ae200, {0x6a, 0xcf, 0xca, 0xc, 0xb7, 0x20, 0x41, 0xb0, 0xc3, ...})
2023-11-14T14:25:27.9081167Z 	/actions-runner/_work/iota-core/iota-core/pkg/protocol/engine/engine.go:290 +0xce
2023-11-14T14:25:27.9082300Z github.com/iotaledger/iota-core/pkg/protocol.(*Protocol).runNetworkProtocol.func1({0x6a, 0xcf, 0xca, 0xc, 0xb7, 0x20, 0x41, 0xb0, 0xc3, 0xc9, ...}, ...)
2023-11-14T14:25:27.9082936Z 	/actions-runner/_work/iota-core/iota-core/pkg/protocol/protocol_network.go:24 +0x5e
2023-11-14T14:25:27.9083397Z github.com/iotaledger/hive.go/runtime/event.(*Event2[...]).Trigger.func1.1()
2023-11-14T14:25:27.9084407Z 	/home/runner/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231110191152-7135670285dc/event/events.go:134 +0x42
2023-11-14T14:25:27.9084858Z github.com/iotaledger/hive.go/runtime/workerpool.(*Task).run(0xc01d2659b0)
2023-11-14T14:25:27.9085869Z 	/home/runner/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231110191152-7135670285dc/workerpool/task.go:48 +0x72
2023-11-14T14:25:27.9086449Z github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).workerReadLoop(0xc00774c150)
2023-11-14T14:25:27.9087525Z 	/home/runner/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231110191152-7135670285dc/workerpool/workerpool.go:190 +0x25
2023-11-14T14:25:27.9088037Z github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).worker(0xc00774c150)
2023-11-14T14:25:27.9089149Z 	/home/runner/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231110191152-7135670285dc/workerpool/workerpool.go:170 +0x50
2023-11-14T14:25:27.9089845Z created by github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).startWorkers in goroutine 337266
2023-11-14T14:25:27.9090938Z 	/home/runner/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231110191152-7135670285dc/workerpool/workerpool.go:162 +0x25
2023-11-14T14:25:27.9091321Z FAIL	github.com/iotaledger/iota-core/pkg/tests	280.159s
2023-11-14T14:25:27.9091444Z FAIL
```

**Comment by jonastheis** [comment]
I've been running this test without and with `-race` for more than 30min on latest develop [b13c7de](https://github.com/iotaledger/iota-core/commit/b13c7dee4082c02f44268abf4d614c7ab564cee8) and could not observe this anymore. Closing issue for now.
