### ISSUE TITLE
panic: cannot open DBInstance that is shutdown

### ISSUE THREAD

**Issue by alexsporn** [iotaledger/iota-core#542]
```
ode-2-validator-1  | 2023-11-21T16:10:09Z	ERROR	Protocol	app@v0.0.0-20231113110812-4ca2b6cc9a42/component.go:115	ProtocolError, error: key not found: failed to get from tree: failed to check if key exists: failed to set new spent output in state tree, outputID: OutputID(0x013bc48c5cd827bef9eaccb42293f09e948acef6ae1bcdbda6209544c2aa1d18110000001300:17): failed to rollback ledger to slot 39: failed to rollback storage to slot 39: error creating new candidate engine
node-2-validator-1  | panic: cannot open DBInstance that is shutdown
node-2-validator-1  | 
node-2-validator-1  | goroutine 283 [running]:
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/storage/database.(*DBInstance).Open(0x41ad860?)
node-2-validator-1  | 	/scratch/iota-core/pkg/storage/database/db_instance.go:92 +0xbe
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/storage/database.(*openableKVStore).instance(0x2c4d000?)
node-2-validator-1  | 	/scratch/iota-core/pkg/storage/database/openablekvstore.go:41 +0x37
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/storage/database.(*openableKVStore).Set(0xc159b1b900, {0xc07d539260, 0x24, 0x24}, {0x41ad860, 0x0, 0x0})
node-2-validator-1  | 	/scratch/iota-core/pkg/storage/database/openablekvstore.go:99 +0x4f
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/storage/database.(*lockedKVStore).Set(0x267753858727d220?, {0xc07d539260?, 0x72ca08efb5dfcf2b?, 0x9ff1d69bd087df05?}, {0x41ad860?, 0x20?, 0x20?})
node-2-validator-1  | 	/scratch/iota-core/pkg/storage/database/lockedkvstore.go:90 +0xf5
node-2-validator-1  | github.com/iotaledger/hive.go/kvstore.(*TypedStore[...]).Set(0x0, {0x20, 0xd2, 0x27, 0x87, 0x85, 0x53, 0x77, 0x26, 0x6a, ...}, ...)
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/kvstore@v0.0.0-20231110191152-7135670285dc/typedstore.go:85 +0x16b
node-2-validator-1  | github.com/iotaledger/hive.go/ads.(*authenticatedMap[...]).Set(0x2c7dec0, {0x20, 0xd2, 0x27, 0x87, 0x85, 0x53, 0x77, 0x26, 0x6a, ...}, ...)
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ads@v0.0.0-20231110191152-7135670285dc/map_impl.go:103 +0x45e
node-2-validator-1  | github.com/iotaledger/hive.go/ads.(*authenticatedSet[...]).Add(...)
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ads@v0.0.0-20231110191152-7135670285dc/set_impl.go:28
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*StateDiff).AddTransaction(0xc159b1b980, 0xc12802ec40, 0xc000494600)
node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/state_diff.go:80 +0x103
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*MemPool[...]).setupTransaction.func1()
node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/mempool.go:488 +0x17d
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*MemPool[...]).setupTransaction.(*inclusionFlags).OnAccepted.func7(0xea?)
node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/inclusion_flags.go:54 +0x1b
node-2-validator-1  | github.com/iotaledger/hive.go/ds/reactive.(*variable[...]).Compute(0x2c7c180?, 0xc15fcef968)
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/reactive/variable_impl.go:56 +0x122
node-2-validator-1  | github.com/iotaledger/hive.go/ds/reactive.(*variable[...]).Set(...)
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/reactive/variable_impl.go:44
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*TransactionMetadata).setup.func3({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/transaction_metadata.go:305 +0xcd
node-2-validator-1  | github.com/iotaledger/hive.go/ds/reactive.(*variable[...]).Compute(0x2c7ca20?, 0xe1ccd1)
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/reactive/variable_impl.go:56 +0x2c6
node-2-validator-1  | github.com/iotaledger/hive.go/ds/reactive.(*variable[...]).Set(...)
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/reactive/variable_impl.go:44
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*TransactionMetadata).markAttachmentIncluded(0xc12802ec40, {0x2d, 0xa8, 0x73, 0x65, 0x6b, 0x2b, 0xc1, 0xe, 0x31, ...})
node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/transaction_metadata.go:332 +0x1bf
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*MemPool[...]).updateAttachment(0xc0986c7308?, {0x2d, 0xa8, 0x73, 0x65, 0x6b, 0x2b, 0xc1, 0xe, 0x31, ...}, ...)
node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/mempool.go:427 +0x162
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*MemPool[...]).MarkAttachmentIncluded(...)
node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/mempool.go:145
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/ledger/ledger.(*Ledger).TrackBlock(0xc0001cde40, 0x926eb1?)
node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/ledger/ledger/ledger.go:222 +0x92
node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine.(*Engine).acceptanceHandler.func1(0xc15fcefed8?)
node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/engine.go:437 +0x3d
node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1.1()
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:86 +0x1f
node-2-validator-1  | github.com/iotaledger/hive.go/runtime/workerpool.(*Task).run(0xc15c24acc0)
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/workerpool/task.go:48 +0x72
node-2-validator-1  | github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).workerReadLoop(0xc0002f9570)
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/workerpool/workerpool.go:190 +0x25
node-2-validator-1  | github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).worker(0xc0002f9570)
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/workerpool/workerpool.go:170 +0x50
node-2-validator-1  | created by github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).startWorkers in goroutine 1
node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/workerpool/workerpool.go:162 +0x25
```

**Comment by piotrm50** [comment]
After resolving the above error, the following happened:

```
ocker-network-node-2-validator-1  | 2023-11-22T13:27:38Z	WARN	Protocol	app@v0.0.0-20231113110812-4ca2b6cc9a42/component.go:152	Booker BlockInvalid, blockID: BlockID(0xd68d91508cda37efac2f536f1293b080fbd51c62005b37ea3ba27a9371dfdc6327000000:39), error: %!w(<nil>): shallow like parent BlockID(0x62c465bd9fb4b05a43b12ab62f6e8d000dd1908325107f0e3ad133f088e3217120000000:32) does not contain a conflicting transaction: failed to inherit conflicts for block BlockID(0xd68d91508cda37efac2f536f1293b080fbd51c62005b37ea3ba27a9371dfdc6327000000:39): failed to book block
docker-network-node-2-validator-1  | 2023-11-22T13:27:39Z	ERROR	Protocol	app@v0.0.0-20231113110812-4ca2b6cc9a42/component.go:115	ProtocolError, error: slot 31 is older than last evicted slot 31: failed to get state diff for slot 31: ledger: engine (e6422471)
docker-network-node-2-validator-1  | panic: runtime error: invalid memory address or nil pointer dereference
docker-network-node-2-validator-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xce405c]
docker-network-node-2-validator-1  |
docker-network-node-2-validator-1  | goroutine 188 [running]:
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*StateDiff).AddTransaction(0x0, 0x401a40f6c0, 0x40000e47a0)
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/state_diff.go:79 +0x4c
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*MemPool[...]).setupTransaction.func1()
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/mempool.go:488 +0x11c
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*MemPool[...]).setupTransaction.(*inclusionFlags).OnAccepted.func7(0x7b?)
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/inclusion_flags.go:54 +0x2c
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/ds/reactive.(*variable[...]).Compute(0x2a70ce0?, 0xf547626c2eb40e0f)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/reactive/variable_impl.go:56 +0x148
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/ds/reactive.(*variable[...]).Set(...)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/reactive/variable_impl.go:44
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*TransactionMetadata).setConflictAccepted(0x401a40f6c0)
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/transaction_metadata.go:244 +0xcc
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/v1.(*MemPool[...]).setup.func1()
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/v1/mempool.go:474 +0x4c
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1(0x400046f3e0?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:88 +0x230
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/ds/orderedmap.(*OrderedMap[...]).ForEach(0xcd7a70, 0x403b5af358?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/orderedmap/orderedmap.go:130 +0x140
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger(0x403b5af408?, {0x5, 0x7e, 0xfc, 0x9b, 0x49, 0x48, 0x8e, 0xad, 0x93, ...})
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:70 +0xc4
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/conflictdag/conflictdagv1.(*ConflictDAG[...]).CreateConflict.func1.1.2(0xf4?)
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/conflictdag/conflictdagv1/conflictdag.go:91 +0xd8
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event2[...]).Trigger.func1(0x40148042a0?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:136 +0x1e8
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/ds/orderedmap.(*OrderedMap[...]).ForEach(0x2a7a380, 0x403b5af4f8?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/orderedmap/orderedmap.go:130 +0x140
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event2[...]).Trigger(0xb7a001?, 0x18?, 0x0?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:118 +0xac
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/conflictdag/conflictdagv1.(*Conflict[...]).setAcceptanceState(0x2a95480, 0x1)
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/conflictdag/conflictdagv1/conflict.go:521 +0xd0
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/conflictdag/conflictdagv1.NewConflict[...].func1()
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/conflictdag/conflictdagv1/conflict.go:116 +0x60
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1(0x4013ca1e00?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:88 +0x200
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/ds/orderedmap.(*OrderedMap[...]).ForEach(0xb77260, 0x403b5af668?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/orderedmap/orderedmap.go:130 +0x140
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger(0x1000edceff868?, {0x4013ca19f8?, 0xebee10?, 0xf8?})
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:70 +0xb4
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/core/weight.(*Weight).AddVoter(0x401aa99950, 0x80?)
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/core/weight/weight.go:88 +0x64
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/conflictdag/conflictdagv1.(*Conflict[...]).ApplyVote(0x2a95480, 0x401eac3e50)
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/conflictdag/conflictdagv1/conflict.go:227 +0x168
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/mempool/conflictdag/conflictdagv1.(*ConflictDAG[...]).CastVotes(0x2a9ad40, 0x401e4b9090, {0x2a70840, 0x40396fad40})
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/mempool/conflictdag/conflictdagv1/conflictdag.go:329 +0x214
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/ledger/ledger.(*Ledger).blockPreAccepted(0x400028b130, 0x40170689a0)
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/ledger/ledger/ledger.go:772 +0x2c4
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1(0x400046fb00?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:88 +0x1b8
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/ds/orderedmap.(*OrderedMap[...]).ForEach(0xb72450, 0x403b5afbe8?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/orderedmap/orderedmap.go:130 +0x140
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger(0x401b190b00?, 0x403b5afc58?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:70 +0xa8
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1(0x40002a4660?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:88 +0x1b8
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/ds/orderedmap.(*OrderedMap[...]).ForEach(0xcb94b4, 0x403b5afd08?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231113110812-4ca2b6cc9a42/orderedmap/orderedmap.go:130 +0x140
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger(0x403f904000?, 0xb?)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:70 +0xa8
docker-network-node-2-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/consensus/blockgadget/thresholdblockgadget.(*Gadget).TrackWitnessWeight(0x400025abd0, 0x4033d3ac60)
docker-network-node-2-validator-1  | 	/scratch/iota-core/pkg/protocol/engine/consensus/blockgadget/thresholdblockgadget/witness_weight.go:67 +0x264
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1.1()
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/event/events.go:86 +0x2c
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/workerpool.(*Task).run(0x403f88e7b0)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/workerpool/task.go:48 +0x74
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).workerReadLoop(0x400025ac40)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/workerpool/workerpool.go:190 +0x28
docker-network-node-2-validator-1  | github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).worker(0x400025ac40)
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/workerpool/workerpool.go:170 +0x54
docker-network-node-2-validator-1  | created by github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).startWorkers in goroutine 1
docker-network-node-2-validator-1  | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231113110812-4ca2b6cc9a42/workerpool/workerpool.go:162 +0x2c
```

**Comment by PhilippGackstatter** [comment]
I got another one of these errors on #551 on commit `36839074418d667cf92725e7f689112fbbba1650` when running `go test -tags rocksdb github.com/iotaledger/iota-core/pkg/tests` (which has develop up to `0a0c1baf49811047b97c1a3714ad316b7634df93` (#570) merged in. Perhaps that PR reintroduced it?

```
panic: cannot open DBInstance that is shutdown

goroutine 233876 [running]:
github.com/iotaledger/iota-core/pkg/storage/database.(*DBInstance).Open(0x495d68?)
	~/git/iota-core/pkg/storage/database/db_instance.go:122 +0xbe
github.com/iotaledger/iota-core/pkg/storage/database.NewDBInstance.func1()
	~/git/iota-core/pkg/storage/database/db_instance.go:43 +0xac
github.com/iotaledger/iota-core/pkg/storage/database.(*openableKVStore).instance(0xc00049fc78?)
	~/git/iota-core/pkg/storage/database/openablekvstore.go:42 +0x29
github.com/iotaledger/iota-core/pkg/storage/database.(*openableKVStore).Get(0xc01a784580, {0xc00faad620, 0x24, 0x24})
	~/git/iota-core/pkg/storage/database/openablekvstore.go:94 +0x31
github.com/iotaledger/iota-core/pkg/storage/database.(*lockedKVStore).Get(0xc01512f440, {0xc00faad620, 0x24, 0x24})
	~/git/iota-core/pkg/storage/database/lockedkvstore.go:82 +0xab
github.com/iotaledger/iota-core/pkg/storage/prunable/slotstore.(*Blocks).Load(0xc01b17bbc0, {0x93, 0xc, 0xbe, 0xd0, 0xff, 0x9f, 0x2f, 0x29, 0x77, ...})
	~/git/iota-core/pkg/storage/prunable/slotstore/blocks.go:26 +0x7d
github.com/iotaledger/iota-core/pkg/protocol/engine.(*Engine).Block(0xc0059fc480, {0x93, 0xc, 0xbe, 0xd0, 0xff, 0x9f, 0x2f, 0x29, 0x77, ...})
	~/git/iota-core/pkg/protocol/engine/engine.go:310 +0x185
github.com/iotaledger/iota-core/pkg/protocol.(*Protocol).runNetworkProtocol.func1({0x93, 0xc, 0xbe, 0xd0, 0xff, 0x9f, 0x2f, 0x29, 0x77, 0xe1, ...}, ...)
	~/git/iota-core/pkg/protocol/protocol_network.go:24 +0x5e
github.com/iotaledger/hive.go/runtime/event.(*Event2[...]).Trigger.func1.1()
	~/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231127134220-90b88e35bdb2/event/events.go:134 +0x42
github.com/iotaledger/hive.go/runtime/workerpool.(*Task).run(0xc01c31d050)
	~/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231127134220-90b88e35bdb2/workerpool/task.go:48 +0x72
github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).workerReadLoop(0xc01d99db90)
	~/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231127134220-90b88e35bdb2/workerpool/workerpool.go:190 +0x25
github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).worker(0xc01d99db90)
	~/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231127134220-90b88e35bdb2/workerpool/workerpool.go:170 +0x50
created by github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).startWorkers in goroutine 233874
	~/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231127134220-90b88e35bdb2/workerpool/workerpool.go:162 +0x25
FAIL	github.com/iotaledger/iota-core/pkg/tests	94.265s
FAIL
```
