### ISSUE TITLE
Crash caused by disconnected neighbor

### ISSUE THREAD

**Issue by shufps** [iotaledger/iota-core#599]
A single virtual machine crashed on our hosting provider, leading to panic among all connected nodes:

```
iota-core          | 2023-12-01T10:33:48Z	INFO	P2P	p2p/neighbor.go:179	Stream closed	{"id": "12D3KooWLMcqCFJhSggjpvSYWDp1HA7zdccmcJC8nz8Lr4bRYzdB", "localAddr": "/ip4/172.18.0.6/tcp/14666", "remoteAddr": "/ip4/10.0.0.8/tcp/14666", "protocol": "iota-core/1.0.0"}
iota-core          | 2023-12-01T10:33:48Z	WARN	P2P	p2p/neighbor.go:121	Failed to disconnect	{"id": "12D3KooWLMcqCFJhSggjpvSYWDp1HA7zdccmcJC8nz8Lr4bRYzdB", "localAddr": "/ip4/172.18.0.6/tcp/14666", "remoteAddr": "/ip4/10.0.0.8/tcp/14666", "err": "stream reset"}
iota-core          | 2023-12-01T10:33:48Z	INFO	P2P	p2p/neighbor.go:138	Exit writeLoop due to canceled context	{"id": "12D3KooWLMcqCFJhSggjpvSYWDp1HA7zdccmcJC8nz8Lr4bRYzdB", "localAddr": "/ip4/172.18.0.6/tcp/14666", "remoteAddr": "/ip4/10.0.0.8/tcp/14666"}
iota-core          | 
iota-core          | goroutine 181 [running]:
iota-core          | 	/scratch/pkg/protocol/sybilprotection/sybilprotectionv1/performance/performance.go:253 +0x3f3
iota-core          | 	/go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231127134220-90b88e35bdb2/shrinkingmap/shrinkingmap.go:165 +0x278
iota-core          | 	/scratch/pkg/core/account/accounts.go:125
iota-core          | 	/scratch/pkg/protocol/sybilprotection/sybilprotectionv1/performance/performance.go:214 +0x369
iota-core          | 	/scratch/pkg/protocol/sybilprotection/sybilprotectionv1/sybilprotection.go:190 +0x2d2
iota-core          | 	/scratch/pkg/protocol/engine/notarization/slotnotarization/manager.go:215 +0x559
iota-core          | 	/scratch/pkg/protocol/engine/notarization/slotnotarization/manager.go:179 +0x92
iota-core          | 	/scratch/pkg/protocol/engine/notarization/slotnotarization/manager.go:108 +0x45
iota-core          | 	/scratch/pkg/protocol/engine/notarization/slotnotarization/manager.go:72 +0x131
iota-core          | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231128121006-331a9e522dfe/event/events.go:86 +0x1f
iota-core          | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231128121006-331a9e522dfe/workerpool/task.go:48 +0x72
iota-core          | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231128121006-331a9e522dfe/workerpool/workerpool.go:190 +0x25
iota-core          | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231128121006-331a9e522dfe/workerpool/workerpool.go:170 +0x50
iota-core          | 	/go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231128121006-331a9e522dfe/workerpool/workerpool.go:162 +0x25

```

**Comment by shufps** [comment]
Another node logged the same but an additional log line with a `panic`:

```
panic: failed to calculate decayed initial reward: wrong epoch index: the reward epoch was bigger than the claiming epoch: 1 > 0: failed to calculate target reward for slot 8196: failed to calculate pool rewards for account 0xacc9c2f61da46acea81e2f022ef86ff95d941a0bc307d966ecf11c8daad8a44a
```

**Comment by shufps** [comment]
According to Max it is already fixed. Will update my installation 😁

**Comment by PhilippGackstatter** [comment]
Fixed by https://github.com/iotaledger/iota-core/pull/593.
