### ISSUE TITLE
Panic on rewards calculation overflow

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/iota-core#614]
While running committee rotation tests in DockerTestFramework ( https://github.com/iotaledger/iota-core/pull/600), nodes panic because the rewards calculation overflow.

To reproduce the errors, checkout to  https://github.com/iotaledger/iota-core/pull/600, and run the `Test_SmallerCommittee` in `tools/docker-network/tests/committee_rotation.go`. With `go.work`, every library is the latest version.

Here's the protocol parameters setup:

```
committeeTargetSize = 4
slotsPerEpochExponent = 4
livenessThresholdUpperBound = 10
livenessThresholdLowerBound = 10
minCommittableAge = 2
maxCommittableAge = 4
epochNearingThreshold=8
```

And the logs:
```
2023-12-07T06:20:56Z	DEBUG	Protocol	app/component.go:98	ConfirmedTimeUpdated, slot: 38 @ 2023-12-07 06:20:55.090446205 +0000 UTC
panic: integer under- or overflow: 2476192049932568352 * 10: failed to calculate pool reward without fixed costs due to overflow for slot 36: failed to calculate pool rewards for account 0x6aee704f25558e8aa7630fed0121da53074188abc423b3c5810f80be4936eb6e

goroutine 381 [running]:
github.com/iotaledger/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1/performance.(*Tracker).ApplyEpoch.func1({0x6a, 0xee, 0x70, 0x4f, 0x25, 0x55, 0x8e, 0x8a, 0xa7, 0x63, ...}, ...)
	/scratch/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1/performance/performance.go:253 +0x3f3
github.com/iotaledger/hive.go/ds/shrinkingmap.(*ShrinkingMap[...]).ForEach(0x2e0d9c0, 0xc000ebd618)
	/scratch/hive.go/ds/shrinkingmap/shrinkingmap.go:174 +0x275
github.com/iotaledger/iota-core/pkg/core/account.(*Accounts).ForEach(...)
	/scratch/iota-core/pkg/core/account/accounts.go:125
github.com/iotaledger/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1/performance.(*Tracker).ApplyEpoch(0xc0004f8500, 0x1, 0xc00142da00)
	/scratch/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1/performance/performance.go:214 +0x369
github.com/iotaledger/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1.(*SybilProtection).CommitSlot(0xc000634bb0, 0x24)
	/scratch/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1/sybilprotection.go:190 +0x2d2
github.com/iotaledger/iota-core/pkg/protocol/engine/notarization/slotnotarization.(*Manager).createCommitment(0xc0003760f0, 0x24)
	/scratch/iota-core/pkg/protocol/engine/notarization/slotnotarization/manager.go:227 +0x559
github.com/iotaledger/iota-core/pkg/protocol/engine/notarization/slotnotarization.(*Manager).tryCommitSlotUntil(0xc0003760f0, 0x26)
	/scratch/iota-core/pkg/protocol/engine/notarization/slotnotarization/manager.go:191 +0x92
github.com/iotaledger/iota-core/pkg/protocol/engine/notarization/slotnotarization.(*Manager).tryCommitUntil(0xc0003760f0, 0x26)
	/scratch/iota-core/pkg/protocol/engine/notarization/slotnotarization/manager.go:120 +0x45
github.com/iotaledger/iota-core/components/protocol.provide.func1.NewProvider.func14.1.1(0xc000ebded8?)
	/scratch/iota-core/pkg/protocol/engine/notarization/slotnotarization/manager.go:78 +0x131
github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1.1()
	/scratch/hive.go/runtime/event/events.go:86 +0x1f
github.com/iotaledger/hive.go/runtime/workerpool.(*Task).run(0xc001a9f080)
	/scratch/hive.go/runtime/workerpool/task.go:48 +0x72
github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).workerReadLoop(0xc00028ec40)
	/scratch/hive.go/runtime/workerpool/workerpool.go:190 +0x25
github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).worker(0xc00028ec40)
	/scratch/hive.go/runtime/workerpool/workerpool.go:170 +0x50
created by github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).startWorkers in goroutine 354
	/scratch/hive.go/runtime/workerpool/workerpool.go:162 +0x25

```

**Comment by TeeVeeEss** [comment]
Similar error for  `calculate pool scaled reward due to overflow`:
```
node-1-validator-1  | panic: integer under- or overflow: 1431655764 * 885556889190: failed to calculate pool scaled reward due to overflow for slot 8196: failed to calculate pool rewards for account 0x6aee704f25558e8aa7630fed0121da53074188abc423b3c5810f80be4936eb6e
node-1-validator-1  |
node-1-validator-1  | goroutine 256 [running]:
node-1-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1/performance.(*Tracker).ApplyEpoch.func1({0x6a, 0xee, 0x70, 0x4f, 0x25, 0x55, 0x8e, 0x8a, 0xa7, 0x63, ...}, ...)
node-1-validator-1  |   /scratch/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1/performance/performance.go:253 +0x3f3
node-1-validator-1  | github.com/iotaledger/hive.go/ds/shrinkingmap.(*ShrinkingMap[...]).ForEach(0x2e0cd20, 0xc01702b618)
node-1-validator-1  |   /go/pkg/mod/github.com/iotaledger/hive.go/ds@v0.0.0-20231206114953-6a65a82e30ad/shrinkingmap/shrinkingmap.go:174 +0x278
node-1-validator-1  | github.com/iotaledger/iota-core/pkg/core/account.(*Accounts).ForEach(...)
node-1-validator-1  |   /scratch/iota-core/pkg/core/account/accounts.go:125
node-1-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1/performance.(*Tracker).ApplyEpoch(0xc0003c5700, 0x0, 0xc010ab7980)
node-1-validator-1  |   /scratch/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1/performance/performance.go:214 +0x369
node-1-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1.(*SybilProtection).CommitSlot(0xc0007474a0, 0x2004)
node-1-validator-1  |   /scratch/iota-core/pkg/protocol/sybilprotection/sybilprotectionv1/sybilprotection.go:190 +0x2d2
node-1-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/notarization/slotnotarization.(*Manager).createCommitment(0xc0004563c0, 0x2004)
node-1-validator-1  |   /scratch/iota-core/pkg/protocol/engine/notarization/slotnotarization/manager.go:227 +0x559
node-1-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/notarization/slotnotarization.(*Manager).tryCommitSlotUntil(0xc0004563c0, 0x200e)
node-1-validator-1  |   /scratch/iota-core/pkg/protocol/engine/notarization/slotnotarization/manager.go:191 +0x92
node-1-validator-1  | github.com/iotaledger/iota-core/pkg/protocol/engine/notarization/slotnotarization.(*Manager).tryCommitUntil(0xc0004563c0, 0x200e)
node-1-validator-1  |   /scratch/iota-core/pkg/protocol/engine/notarization/slotnotarization/manager.go:120 +0x45
node-1-validator-1  | github.com/iotaledger/iota-core/components/protocol.provide.func1.NewProvider.func14.1.1(0xc01702bed8?)
node-1-validator-1  |   /scratch/iota-core/pkg/protocol/engine/notarization/slotnotarization/manager.go:78 +0x131
node-1-validator-1  | github.com/iotaledger/hive.go/runtime/event.(*Event1[...]).Trigger.func1.1()
node-1-validator-1  |   /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231206114953-6a65a82e30ad/event/events.go:86 +0x1f
node-1-validator-1  | github.com/iotaledger/hive.go/runtime/workerpool.(*Task).run(0xc00b8c11d0)
node-1-validator-1  |   /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231206114953-6a65a82e30ad/workerpool/task.go:48 +0x72
node-1-validator-1  | github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).workerReadLoop(0xc00026c930)
node-1-validator-1  |   /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231206114953-6a65a82e30ad/workerpool/workerpool.go:190 +0x25
node-1-validator-1  | github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).worker(0xc00026c930)
node-1-validator-1  |   /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231206114953-6a65a82e30ad/workerpool/workerpool.go:170 +0x50
node-1-validator-1  | created by github.com/iotaledger/hive.go/runtime/workerpool.(*WorkerPool).startWorkers in goroutine 232
node-1-validator-1  |   /go/pkg/mod/github.com/iotaledger/hive.go/runtime@v0.0.0-20231206114953-6a65a82e30ad/workerpool/workerpool.go:162 +0x25

```

**Comment by karimodm** [comment]
Should be fixed by https://github.com/iotaledger/iota.go/pull/641
